export const teachersData = [
    {
        id: "T1001",
        name: "Alice Johnson",
        subjects: ["Mathematics", "Physics"],
        classes: ["10A", "10B", "11A"],
        phone: "555-0101",
        address: "123 Maple Ave, Springfield",
        avatar: "https://i.pravatar.cc/150?u=T1001",
    },
    {
        id: "T1002",
        name: "Bob Smith",
        subjects: ["English", "History"],
        classes: ["9A", "9B"],
        phone: "555-0102",
        address: "456 Oak Ln, Springfield",
        avatar: "https://i.pravatar.cc/150?u=T1002",
    },
    {
        id: "T1003",
        name: "Carol Williams",
        subjects: ["Biology", "Chemistry"],
        classes: ["11B", "12A"],
        phone: "555-0103",
        address: "789 Pine St, Springfield",
        avatar: "https://i.pravatar.cc/150?u=T1003",
    },
    {
        id: "T1004",
        name: "David Brown",
        subjects: ["Computer Science"],
        classes: ["10A", "11A", "12A"],
        phone: "555-0104",
        address: "101 Elm St, Springfield",
        avatar: "https://i.pravatar.cc/150?u=T1004",
    },
    {
        id: "T1005",
        name: "Eva Davis",
        subjects: ["Art", "Design"],
        classes: ["9A", "10B"],
        phone: "555-0105",
        address: "202 Cedar Dr, Springfield",
        avatar: "https://i.pravatar.cc/150?u=T1005",
    },
    {
        id: "T1006",
        name: "Frank Miller",
        subjects: ["Physical Education"],
        classes: ["All"],
        phone: "555-0106",
        address: "303 Birch Blvd, Springfield",
        avatar: "https://i.pravatar.cc/150?u=T1006",
    },
    {
        id: "T1007",
        name: "Grace Wilson",
        subjects: ["Geography"],
        classes: ["9B", "10A"],
        phone: "555-0107",
        address: "404 Walnut Way, Springfield",
        avatar: "https://i.pravatar.cc/150?u=T1007",
    },
    {
        id: "T1008",
        name: "Henry Moore",
        subjects: ["Music"],
        classes: ["All"],
        phone: "555-0108",
        address: "505 Ash Ct, Springfield",
        avatar: "https://i.pravatar.cc/150?u=T1008",
    },
    {
        id: "T1009",
        name: "Isabel Taylor",
        subjects: ["Spanish", "French"],
        classes: ["11A", "12B"],
        phone: "555-0109",
        address: "606 Spruce St, Springfield",
        avatar: "https://i.pravatar.cc/150?u=T1009",
    },
    {
        id: "T1010",
        name: "Jack Anderson",
        subjects: ["Economics"],
        classes: ["12A", "12B"],
        phone: "555-0110",
        address: "707 Fir Ln, Springfield",
        avatar: "https://i.pravatar.cc/150?u=T1010",
    },
];
